### ISSUE TITLE
!points

### ISSUE THREAD

**Issue by alexthewood** [Bonfire/Legionary#10]
Recognise !points command 

!points bump
!points guide
!points event

Each separate command recognised will be moved to a separate channel for leadership+. Every secondary command following !points will have an individual channel. There will be a channel for bump, guide, events etc. That way it will be easier to view and recognise who needs points approved.

Approve command will be given by !approve <username>. I’m not sure how you could integrate it to work if the same person requested multiple !requests. Perhaps !approve <username> <bump>

**Comment by Bonfire** [comment]
Given how the points are doled out, this isn't necessary anymore. Closing.
